#!/usr/bin/python
# Example using a character LCD plate.
import time

import Adafruit_CharLCD as LCD
import time`

# Initialize the LCD using the pins 
lcd = LCD.Adafruit_CharLCDPlate()

while 1:
	lcd.clear()
	lcd.message("Hello World")
	sleep(2)
	lcd.clear
	lcd.message("Hello/nWorld")
